"use client";

export default function TermsPage() {
  return (
    <main className="min-h-screen" style={{ background: "#fff7ed" }}>
      <nav className="bg-white border-b sticky top-0 z-40" style={{ borderColor: "#fed7aa" }}>
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center" style={{ background: "linear-gradient(135deg, #f97316, #ea580c)" }}>
              <span className="text-white font-black text-sm">N</span>
            </div>
            <span className="font-black text-gray-900 text-lg">NutriScan <span style={{ color: "#f97316" }}>AI</span></span>
          </a>
          <a href="/" className="text-sm text-gray-500 hover:text-gray-900">← Back</a>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-black text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: May 2025 · NutriScan AI by Pradeep Banoth</p>

        <div className="bg-white rounded-3xl border shadow-sm p-8 space-y-8" style={{ borderColor: "#fed7aa" }}>
          <div className="p-4 rounded-2xl text-sm text-gray-600 leading-relaxed" style={{ background: "#fff7ed" }}>
            By using NutriScan AI, you agree to these terms. NutriScan AI is currently a free service built and operated by Pradeep Banoth, Telangana, India.
          </div>

          {[
            {
              title: "Using the app",
              items: [
                "You must be at least 10 years old to use NutriScan AI.",
                "You are responsible for keeping your account credentials secure.",
                "You must not misuse, hack, or attempt to damage the service.",
                "You must not use the app for any illegal purpose.",
              ]
            },
            {
              title: "Health disclaimer",
              items: [
                "NutriScan AI is NOT a medical app and does NOT provide medical advice.",
                "All health scores and AI analysis are for general informational purposes only.",
                "Do not make medical or dietary decisions based solely on our analysis.",
                "Always consult a qualified doctor or nutritionist for health decisions.",
                "Product data comes from OpenFoodFacts and may not always be accurate or up to date.",
              ]
            },
            {
              title: "AI analysis disclaimer",
              items: [
                "Our health scores are generated by AI and may not be 100% accurate.",
                "We do not guarantee the completeness or correctness of any analysis.",
                "AI recommendations are general in nature and not personalized medical advice.",
              ]
            },
            {
              title: "Our rights",
              items: [
                "We may update or change the app at any time without notice.",
                "We may suspend or terminate accounts that violate these terms.",
                "We may modify these terms at any time — continued use means acceptance.",
              ]
            },
            {
              title: "Limitation of liability",
              items: [
                "NutriScan AI is provided as-is without warranties of any kind.",
                "We are not liable for any damages resulting from use of the app.",
                "We are not responsible for decisions made based on our AI analysis.",
              ]
            },
            {
              title: "Governing law",
              items: [
                "These terms are governed by the laws of India.",
                "Any disputes shall be subject to the jurisdiction of courts in Telangana, India.",
              ]
            },
            {
              title: "Contact",
              items: [
                "For any questions about these terms, email: banothpradeep0203@gmail.com",
                "We will respond within 7 days.",
              ]
            },
          ].map((section) => (
            <div key={section.title}>
              <h2 className="text-base font-black text-gray-900 mb-3">{section.title}</h2>
              <ul className="space-y-2">
                {section.items.map((item, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-gray-600 leading-relaxed">
                    <span className="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0" style={{ background: "#f97316" }} />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="mt-6 text-center">
          <a href="/privacy" className="text-sm font-semibold hover:underline" style={{ color: "#f97316" }}>View Privacy Policy →</a>
        </div>
      </div>
    </main>
  );
}
